### ISSUE TITLE
Can't get the bobpay PaymentHandler to work

### ISSUE THREAD

**Issue by cyberphone** [madmath/payment-request-show#13]
I managed installing bobpay and see it in Chrome/Applications.
Using the following ultra simple code I had hoped to activate bobpay:
https://cyberphone.github.io/doc/payments/paywithbobpay.html

However, the console says the payment method is not recognized.
Any idea what's wrong?

I'm using 62.0.3164.0 (Official Build) canary (64-bit) on Windows 10 which actually _closes the entire browser abruptly_ when I run the bobpay install so something isn't entirely OK here...although the service worker seems to be there anyway which indicates that there could be a problem adding the payment instrument.

**Comment by madmath** [comment]
Hi Anders, 

Chrome does not support Payment Handlers (also called Service Worker payment apps in the code) yet on desktop. This is coming in a few releases.

Perhaps try the same example on Chrome for Android? You'll need to turn on chrome://flags#service-worker-payment-apps and chrome://flags#enable-experimental-web-platform-features for anything to work. 

Hope this helps! Will close this issue.

**Comment by cyberphone** [comment]
Dear @madmath I tried your college's sample 
https://rsolomakhin.github.io/pr/bob
on Android 7.0.0 using Chrome 59.0.3071.125.
The install works (it says so at least...) but Rouslan's sample says "Cannot may payment'.
Found and set flag: chrome://flags#enable-experimental-web-platform-features
Not found flag: chrome://flags#service-worker-payment-apps

**Comment by madmath** [comment]
Hi @cyberphone, I would test with a Dev/Canary version of Chrome for Android (Available on the Play Store), as this is in development and most of the patches have landed in those releases but not in the Stable release.

**Comment by cyberphone** [comment]
It worked! Thanks!

**Comment by biseraivanovska** [comment]
Hi, @cyberphone first thanks for referencing the issue.. I tried( with your example, as well as with BobPayTest example), as you have discussed (with chrome dev), but I still get "payment method not supported".  Cannot understand why :( 

One question though, given the example: ( https://www.xda-developers.com/google-officially-adopts-the-payment-request-api-allowing-you-to-pay-with-3rd-party-apps-in-chrome/ ) there is a mobile app. When you worked on your example, did you do some sample mobile app? 

Thanks,
Bisera.

**Comment by cyberphone** [comment]
Hi @biseraivanovska Well, my intention was really just to see if I could get it to work so I didn't create a `PaymentHandler `method myself.  Unfortunately I don't have much faith in this system for the following reasons:

On the mobile Web you can use a native "App" (mobile wallet) like Android Pay, which is already supported and works quite well.

On the desktop, the market headed by Alipay have _deployed another solution_ which is using QR + mobile wallet. It is technically possible doing a more powerful integration to the mobile wallet but it would only make the `PaymentHandler `an even less attractive option.

This is what some people refer to as "Converged Payments".  A single wallet (and associated enrollments) for every situation (POS, Mobile Web, Desktop Web).

When combined with P2P payments you have a solution the card industry can only dream about!

**Comment by cyberphone** [comment]
@biseraivanovska @madmath @gauntface To put it in another way, you cannot create anything that is even remotely comparable to AndroidPay using current Web technology.  Due to that I early on suggested that instead of designing a payment-specific interface for browsers, one should consider an application-neutral "bridge" between the two powerful technologies we have to play with.  The Web is great, but "Apps" are great as well.

https://github.com/cyberphone/web2native-bridge#api

By combining the power of both worlds you get an _unbeatable combination_.  Unfortunately,  Google  took a pretty "religious" stance on this topic so it was dismissed without any discussions.  Now the very same folks will have to prove that intrinsically crippled technology like the `PaymentHandler` is the future which will be fun to watch the outcome of :-)

I'm personally continuing with "Converged Payments":
https://cyberphone.github.io/doc/saturn/saturn-authorization.pdf

It is not that easy since US tech giant Intel (with some help from Google), _unilaterally_ decided that NFC payments on the Web is not interesting:
https://github.com/w3c/web-nfc/issues/128#issuecomment-308357525
making stone-age QR tech the only credible solution:
https://www.techinasia.com/china-fintech-blueprint-for-rest-of-the-world

**Comment by biseraivanovska** [comment]
@cyberphone It's not about trying to create something more than AndroidPay, for me it does not make any logic, if it's supported by google, why yet the examples don't work? Why the methods are not recognized and therefore the promise is rejected?

Have you tried the AndroidPay example?

**Comment by cyberphone** [comment]
@biseraivanovska I did indeed succeed using https://bobpay.xyz/ and https://rsolomakhin.github.io/pr/bob/ a month ago on Android using Canary.
