### ISSUE TITLE
Bad window URL in service worker = return successful payment

### ISSUE THREAD

**Issue by apowers313** [madmath/payment-request-show#23]
In modifying my own copy of BobPay, I forgot to update the `url` on [line 14 of sw-bobpay.js](https://github.com/madmath/payment-request-show/blob/9a1d581dad116bd30963615026ea5046d2fa1591/bobpay/public/pay/sw-bobpay.js#L14) to point to my payment provider. The result was that when clicking "pay" in the Chrome pop-over, the new window would never open, a "Promise failed" error would get logged to the console, and the payment successful screen with it's associated JSON would appear.

Seems like a failed payment window should lead to a failed payment?

**Comment by madmath** [comment]
Opened a chromium bug for this, thanks! https://bugs.chromium.org/p/chromium/issues/detail?id=776720
